### PR TITLE
add banall&unbanall&ban&unban&kick by reply

### PR DESCRIPTION
**Pull request by hafez16**
add banall&unbanall&ban&unban&kick by reply for supergroup

### CODE REVIEW

**Comment by hfjgjfg** [comment]
add reply for all commands TNX

**Comment by SHIELDTM** [comment]
Good idea
SEEDTEAM, Check please

**Comment by hafez16** [comment]
seed team :-|

**Comment by mobinlord** [comment]
کر

**Comment by mobinlord** [comment]
hi :lollipop:

**Comment by rezaforever** [comment]
Kick command :|
Please debug

**Pull request closed without merging**
