### PR TITLE
mustafa

### PR DESCRIPTION
**Pull request by mustafamarswmy**
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++ libjansson-dev libpython-dev expat libexpat1-dev

### CODE REVIEW

**Comment by mustafamarswmy** [comment]
cd $home

**Comment by mustafamarswmy** [comment]
git clone https://github.com/SEEDTEAM/TeleSeed.git

**Comment by mustafamarswmy** [comment]
cd TeleSeed

**Comment by mustafamarswmy** [comment]
chmod +x launch.sh

**Comment by mustafamarswmy** [comment]
./launch.sh install

**Comment by mustafamarswmy** [comment]
./launch.sh

**Comment by pAyDaAr** [comment]
WTF =\

**Comment by Rondoozle** [comment]
Please do not comment the install instructions.

**Pull request closed without merging**
